CHARACTER*30 NOM1,NOM2
INTEGER*1 DAT(2000000),temp,count
WRITE(*,*) ' INDICA NOMBRE DE ARCHIVO DE IMAGEN'
READ(*,*) NOM1
WRITE(*,*) ' INDICA NOMBRE DE ARCHIVO DE SALIDA'
READ(*,*) NOM2
WRITE(*,*) 'ESCRIBE TAMAÑO EN BYTES'
READ(*,*) NTAM
WRITE(*,*) 'INDICA LARGO DE IMAGEN EN PIXELES'
READ(*,*) NL
WRITE(*,*) 'INDICA ALTO DE IMAGEN EN PIXELES'
READ(*,*) NA
WRITE(*,*) 'INDICA NUMERO DE BYTES POR PIXEL'
READ(*,*) NPIX
OPEN(40,FILE=NOM1,ACCESS='DIRECT',FORM='UNFORMATTED',STATUS='OLD',RECL=NTAM)
READ(40,REC=1)(DAT(I),I=1,NTAM)
!Esto permite iniciar en el primer pixel, nos saltamos el header
NEN=NTAM-NL*NA*NPIX
OPEN(41,FILE=NOM2,ACCESS='DIRECT',FORM='UNFORMATTED',STATUS='unknown',RECL=NTAM)
!DO I=NEN+1,NTAM
!DAT(I)=255-DAT(I)
!ENDDO
!WRITE(41,REC=1)(DAT(I),I=1,NTAM)
count=1
DO I=NEN, ((NTAM)/2)
temp=DAT(I)
DAT(I)=DAT(NTAM-I+NEN)
DAT(NTAM-I+NEN)=temp
count=count+1
END DO

DO I=NEN+2, NTAM-2,3
temp=DAT(I)
DAT(I)=DAT(I+2)
DAT(I+2)=temp
END DO


WRITE(41,REC=1)(DAT(I),I=1,NTAM)
CLOSE (40)
CLOSE (41)
PRINT*,(DAT(I),I=1,10)
END

